name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Pulsar
        run: |
          sudo apt install -y libnotify4 xvfb libsecret-1-0 python3-pip
          pip install yq
          latest_version=$(curl https://github.com/pulsar-edit/pulsar/releases.atom | xq -x '//feed/entry/title' | head -n 1 | sed 's/^v//')
          wget -q "https://github.com/pulsar-edit/pulsar/releases/download/v${latest_version}/Linux.pulsar_${latest_version}_amd64.deb"
          sudo dpkg -i "Linux.pulsar_${latest_version}_amd64.deb"
      - name: Install dependencies
        run: ppm i
      - name: Run tests
        run: xvfb-run -a ppm test
